SELECT me.ID
FROM ECOLI_DATA me
JOIN ECOLI_DATA p ON me.PARENT_ID = p.ID
JOIN ECOLI_DATA gp ON p.PARENT_ID = gp.ID
WHERE p.ID is not NULL and gp.ID is not NULL and gp.PARENT_ID is NULL
ORDER BY me.ID ASC;