SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO i
WHERE REST_ID = (
    SELECT REST_ID
    FROM REST_INFO
    WHERE FOOD_TYPE = i.FOOD_TYPE
    ORDER BY FAVORITES DESC
    LIMIT 1 )
ORDER BY i.FOOD_TYPE DESC;