WITH COUNT_HISTORY
AS (SELECT CAR_ID, COUNT(CAR_ID) AS CNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID)

SELECT MONTH(car.START_DATE) as MONTH, car.CAR_ID, COUNT(car.CAR_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY car
JOIN COUNT_HISTORY cnt ON car.CAR_ID = cnt.CAR_ID
WHERE cnt.CNT >= 5 AND car.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, car.CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;

